version: '3.6'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  
  backend:
    build:
      ./backend
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      ./frontend
    container_name: frontend
    ports:
      - "3001:3001"
    depends_on:
      - db
      - backend


  

